### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OrderedDict'

### ISSUE THREAD

**Issue by Jigar27** [nyu-dl/dl4mt-multi#7]
Hello,
I am using python 2.7.6. while running 'python train_mlnmt.py' I got following error.

File "train_mlnmt.py", line 27, in <module>
    train(config, get_tr_stream(config), get_dev_streams(config),
  File "/home/development/jigar/jigar/dl4mt-multi/mcg/stream.py", line 214, in get_tr_stream
    for k, v in config['src_vocabs'].iteritems()}
  File "/home/development/jigar/jigar/dl4mt-multi/mcg/stream.py", line 214, in <dictcomp>
    for k, v in config['src_vocabs'].iteritems()}
AttributeError: 'module' object has no attribute 'OrderedDict' 

I guess this error is specific to python version earlier to 2.6.

**Comment by orhanf** [comment]
Hi @Jigar27, this error is caused because you probably do not pass `--config` argument to `train_mlnmt.py`, hence it tries to find a configuration just named `config` by default.

Can you please try passing one of the prototypes [here](https://github.com/nyu-dl/dl4mt-multi/blob/master/config.py) for `--config`

Something like:
```python
python train_mlnmt.py --config=prototype_config_multiCG_08
```

**Comment by Jigar27** [comment]
Hello @orhanf ,  thanks for your reply. I am just getting started with this model and this is my first hand on experience so I hope you dont ignore my silly doubts. I tried what you suggested like 


python train_mlnmt.py --config=prototype_config_multiCG_08
Traceback (most recent call last):
  File "train_mlnmt.py", line 23, in <module>
    args.config.split('.')[0] if '.py' in args.config else args.config)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named prototype_config_multiCG_08 

even for prototype_config_singleCG_08 .  Is there still something which I am missing?

**Comment by orhanf** [comment]
Sorry this is my bad, default arguments should work. Or at least you can try:
```python 
python train_mlnmt.py --config=config.py --proto=prototype_config_multiCG_08
```

 Probably you have a path issue, may be you can try adding the working directory to your PYTHONPATH, and be sure you've followed steps in `setup.sh`

**Comment by Jigar27** [comment]
Hello,
I retried with all initial steps. setup.sh worked absolutely fine. But still the following error is persistent. I am having python 2.7.6.

 File "train_mlnmt.py", line 27, in <module>
    train(config, get_tr_stream(config), get_dev_streams(config),
  File "/home/development/jigar/jigar/dl4mt-multi/mcg/stream.py", line 214, in get_tr_stream
    for k, v in config['src_vocabs'].iteritems()}
  File "/home/development/jigar/jigar/dl4mt-multi/mcg/stream.py", line 214, in <dictcomp>
    for k, v in config['src_vocabs'].iteritems()}
AttributeError: 'module' object has no attribute 'OrderedDict'

I also checked sys.path but I couldn't find any unusual thing.
>>> from pprint import pprint as p
>>> import sys
>>> p(sys.path)
['',
 '/home/development/jigar/jigar/codes/GroundHog',
 '/home/development/jigar/.local/lib/python2.7/site-packages/progressbar2-3.15.0-py2.7.egg',
 '/home/development/jigar/.local/lib/python2.7/site-packages/python_utils-2.0.1-py2.7.egg',
 '/home/development/jigar/.local/lib/python2.7/site-packages/pyzmq-16.0.2-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/bz2file-0.98-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg',
 '/home/development/girish/src/tqdm',
 '/usr/local/lib/python2.7/dist-packages/stop_words-2015.2.23.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/nwalign-0.3.1-py2.7-linux-x86_64.egg',
 '/home/development/jigar/jigar/dl4mt_multi',
 '/usr/lib/python2.7',
 '/home/development/jigar/jigar/codes/picklable_itertools',
 '/home/development/jigar/jigar/codes/fuel',
 '/home/development/jigar/jigar/codes/blocks',
 '/home/development/jigar/jigar/dl4mt-multi',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/home/development/jigar/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7']

**Comment by orhanf** [comment]
@Jigar27 what is your python version? this looks like a python issue.

`python --version`

if you are using 2.6 or earlier, code may not work. In that case please point to 2.7 python version.

**Comment by Jigar27** [comment]
It is python 2.7.6.

**Comment by Jigar27** [comment]
Hello @orhanf , I figured out that the following line is responsible for the error. 

///this is a small example
cPickle.load(open('europarl-v7.de-en.de.tok.pkl'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'OrderedDict'

In the given system mcg/stream.py
src_vocabs = {k: cPickle.load(open(v))
                  for k, v in config['src_vocabs'].iteritems()}
this is the line where cPickle is loading the dictionary, the error is getting raised. 
Any suggestion to handle this will be highly appreciated.

**Comment by Jigar27** [comment]
Hello @orhanf , the error has been solved. while loading using pickle I used an extra argument protocol=2
